version: '3'

services:
  # Koa 应用服务
  llm-mini-chat-server:
    build: .
    container_name: llm-mini-chat-server
    ports:
      - "3030:3030"
    depends_on:
      - mysql
      - redis
    networks:
      - llm-mini-chat-network

  # MySQL 数据库服务
  mysql:
    image: mysql:8.0
    container_name:  llm-mini-chat-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=llm-mini-chat_db
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql # 持久化 MySQL 数据
    networks:
      - llm-mini-chat-network

  # Redis 缓存服务
  redis:
    image: redis:6
    container_name: aigc-redis
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data # 持久化 Redis 数据
    networks:
      - llm-mini-chat-network

# 定义卷
volumes:
  mysql-data:
  redis-data:

# 定义网络
networks:
  llm-mini-chat-network:
    driver: bridge # 使用桥接驱动